name: GitHub Pages Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
              ruby-version: 2.7.3 # Specify the Ruby version you want to use


      - name: Install Bundler
        run: gem install bundler

      - name: Install dependencies
        run: bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          bundle exec jekyll build
          cd _site
          git init
          git add .
          git commit -m "GitHub Pages deploy"
          git branch -M main
          git remote add origin ${{ secrets.GITHUB_REPOSITORY }}
          git push -f origin main
